### ISSUE TITLE
url_quote import error

### ISSUE THREAD

**Issue by JacquesVlaming** [radoondas/flask-elastic-image-search#4]
Running in ESS config

(.venv) jacquesvlaming@Jacquess-MBP flask-elastic-image-search %   docker run -p 5001:5001  \
  -e ES_HOST='https://mydeployment.elastic-cloud.com' -e ES_USER='elastic' \
  -e ES_PWD='mypassword' flask-elastic-image-search:0.0.1
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 28, in <module>
    from . import cli
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "/usr/local/lib/python3.9/site-packages/flask/helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.9/site-packages/werkzeug/urls.py)

**Comment by radoondas** [comment]
Hi @JacquesVlaming 
I've encountered this issue and it was solved by adding a correct version of Werkzeug library into `requirements.txt` file. It looks like there is dependency policy that uses newer library version. 

Can you please try to add a line to file `requirements.txt` and then re-run the environment installation, and rebuild the Docker image again. 
Rebuilding the image means copying new requirements file and installing proper dependencies. 
Addition:
Werkzeug==2.2.2

Thanks

**Comment by JacquesVlaming** [comment]
Thank you @radoondas.. That solved it. :)

**Comment by radoondas** [comment]
Great!
I'll update the repository with this change to prevent further issues with the library.
